name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            os: ubuntu-latest
            platform: Android

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@v3
        with:
          bindings: geode-sdk/bindings
          platform: ${{ matrix.config.platform }}
